volumes:
  postgres:
  node_modules:

networks:
  comfortel:

services:
  app_dev:
    build:
      context: .
      target: dev
    container_name: comfortel_backend
    depends_on:
      - postgres
    env_file: [.env]
    ports:
      - '${PORT}:3000'
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - comfortel
    profiles:
      - dev
    command: sh -c "npm run migrate:run && npm run start:dev"

  app_debug:
    build:
      context: .
      target: dev
    container_name: comfortel_backend
    depends_on:
      - postgres
    env_file: [.env]
    ports:
      - '${PORT}:3000'
      - '9229:9229'
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - comfortel
    profiles:
      - debug
    command: sh -c "npm run migrate:run && npm run start:debug"

  postgres:
    image: postgres:15
    container_name: comfortel_postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - comfortel
